const games = [
  { name: "League of Legends", genre: "MOBA" },
  { name: "Dota 2", genre: "MOBA" },
  { name: "Valorant", genre: "Tactical Shooter" },
  { name: "Counter-Strike 2", genre: "Tactical Shooter" },
  { name: "Overwatch 2", genre: "Hero Shooter" },
  { name: "Apex Legends", genre: "Battle Royale" },
  { name: "Fortnite", genre: "Battle Royale" },
  { name: "Minecraft", genre: "Sandbox" },
  { name: "Terraria", genre: "Sandbox" },
  { name: "The Witcher 3", genre: "RPG" },
  { name: "Elden Ring", genre: "Soulslike" },
  { name: "Dark Souls 3", genre: "Soulslike" },
  { name: "Hollow Knight", genre: "Metroidvania" },
  { name: "Celeste", genre: "Platformer" },
  { name: "Hades", genre: "Roguelike" },
  { name: "Balatro", genre: "Indie nice :)" },
  { name: "Stardew Valley", genre: "Farming Sim" },
  { name: "Among Us", genre: "Social Deduction" },
  { name: "Fall Guys", genre: "Party" },
  { name: "Rocket League", genre: "Sports" },
  { name: "FIFA 24", genre: "Sports" },
  { name: "Squad", genre: "Tactical Shooter" },
  { name: "Clash Royale", genre: "Mobile" },
  { name: "Clash of Clans", genre: "Mobile" },
  { name: "Genshin Impact", genre: "Action RPG" },
  { name: "Final Fantasy XIV", genre: "MMORPG" },
  { name: "World of Warcraft", genre: "MMORPG" },
];
